### ISSUE TITLE
Promotional pricining on product: Percentage not saving

### ISSUE THREAD

**Issue by Sanderha** [markguinn/silverstripe-shop-extendedpricing#1]
Hey there

I added the "HasPromotionalPricing" extension to Product. Everything showed up, and all fields work except for the percentage field.
When I type in 50 or 50% and save, it just sets it back to 0%.

Thanks

**Comment by markguinn** [comment]
It's possible something has changed in silverstripe since I built this. What happens if you enter 0.5?

**Comment by Sanderha** [comment]
If I enter 0.5, it returns a validation error : '0.5' is not a number, only numbers can be accepted for this field

**Comment by markguinn** [comment]
Wow, that's vastly different behaviour. What version of SS are you using?

**Comment by Sanderha** [comment]
Im using Silverstripe 3.1.13. I dont think I have anything anywhere else that could conflict and cause this issue

**Comment by markguinn** [comment]
Ok. I'll have a look. If you find the issue first, feel free to submit a pull request.

**Comment by markguinn** [comment]
I just did a fresh install and it's working properly for me. What other extensions do you have on Product? Are there any other PercentageField classes in your project?

**Comment by Sanderha** [comment]
Hmm no other extensions on Product. 
If it helps, I have these shop modules installed:
- discount
- shipping
- extendedpricing
- silverstripe shop

I'll try to set up a clean SS install and see if it works there

**Comment by markguinn** [comment]
What platform are you running? Windows/Mac, XAMPP/MAMP/Vagrant, etc?

**Comment by Sanderha** [comment]
Im running Mac with OSX 10.10, with MAMP. 

Also I just tried not to use the PercentageField, but a normal NumericField. 
When using this, the highest number you can type in is 1.0000  . If I type in 0.1000 it saves perfectly fine, and calculates a 10% discount.

**Comment by markguinn** [comment]
Also, what are your locale settings? I'm looking at NumericField::setValue and it's using Zend framework's locale formatting. Are you by chance in a part of the work that uses a comma instead of a period for the decimal separator?

**Comment by Sanderha** [comment]
Ah that might have something to do with it. My locale is set to da_DK . In Denmark we use a comma to separate decimals

**Comment by markguinn** [comment]
That's got to be it. That's the only difference between our configurations. Sorry my American ignorance of the rest of the world is showing. :)

I don't see anything in PercentageField that looks like it would fail, but I don't see any other options and that explains all the behaviours you're seeing. I don't have time to work on a fix right now but I'll try to give it a look later on. If you want to investigate it yourself there is a unit test for PercentageField that might be helpful.

**Comment by Sanderha** [comment]
Yeah the problem should have something to do with the locale indeed.
Silverstripe does not seem to have a problem with regular NumericFields though, they use commas and work fine, when using the Percentage DB type. 
Im having a hard time figuring out what goes wrong in the PercentageField you made.

Could be great if you'd take a look when you have some time :)

**Comment by markguinn** [comment]
I think this is fixed in master. It's at least passing tests when the locale is set to yours. Could you pull the changes in and verify that it's now working for you?

**Comment by Sanderha** [comment]
Unfortunately the problem persists! 

I tried commenting out the setValue() function on PercentageField, so only the Value() function is left. Then when I enter 50 in the CMS, it saves as 5.000%.. but functions correctly in the template, subtracting 50% from the price.

**Comment by Sanderha** [comment]
Nevermind previous comment.

I decided to make my own custom percentagefield by copying yours, and changing Value() function a bit:

```php
	public function Value() {
		// check if is allowed, has to be a number
		if(!is_numeric($this->value)) return '0%';
		// get our locale
		$locale = new Zend_Locale($this->getLocale());

		$number = $this->value * 100.0;

		// converts it to use comma instead of dot as a decimal separator
		$val = Zend_Locale_Format::toNumber($number, array('locale' => $locale));

		return $val . '%';
	}
```

**Comment by markguinn** [comment]
Thanks for this! Did you happen to run the test suite? I wrote a test against da_DK but it's possible I didn't do enough to fully switch the locale. If the tests pass with your version, would you mind submitting a pull request?

**Comment by Sanderha** [comment]
To be honest im quite a newbie at PHP and programming in general, so I dont know how you guys perform those tests :)

**Comment by markguinn** [comment]
Absolutely no problem. I'll pull your method into my installation this evening and run the tests. If you want to be able to run the tests yourself, you just need to add "phpunit/phpunit" to composer and then run `vendor/bin/phpunit -c shop_extendedpricing/phpunit.dist.xml` or `framework/sake dev/tests/module/shop_extendedpricing` or `framework/sake dev/tests/SpecificTestClass`.

**Comment by Sanderha** [comment]
Interesting. I'll have a look at that, thanks!
